source("../tractor.base/R/analyze.R")
source("../tractor.base/R/dicom.R")
source("../tractor.base/R/files.R")
source("../tractor.base/R/generate.R")
source("../tractor.base/R/internal.R")
source("../tractor.base/R/list_object.R")
source("../tractor.base/R/misc.R")
source("../tractor.base/R/mri_image.R")
source("../tractor.base/R/neighbourhood.R")
source("../tractor.base/R/nifti.R")
source("../tractor.base/R/png.R")
source("../tractor.base/R/vector.R")
source("../tractor.base/R/viz.R")
source("../tractor.base/R/yaml.R")
source("../tractor.base/R/zzz.R")

.First.lib(NULL, NULL)

source("R/flirt.R")
source("R/fsl.R")
source("R/probtrack.R")
source("R/result.R")
source("R/session.R")
source("R/transform.R")
source("R/zzz.R")

.First.lib(NULL, NULL)
