source("R/analyze.R")
source("R/dicom.R")
source("R/files.R")
source("R/generate.R")
source("R/internal.R")
source("R/list_object.R")
source("R/misc.R")
source("R/mri_image.R")
source("R/neighbourhood.R")
source("R/nifti.R")
source("R/png.R")
source("R/vector.R")
source("R/viz.R")
source("R/yaml.R")
source("R/zzz.R")

.First.lib(NULL, NULL)
