library(tractor.graph)
library(igraph)
context("files")

test_that("Principle Networks works fine", {
  PN <- readRDS("testthat/p_network.rds")
  g1 <- readRDS("testthat/testGraph.rds")
  PN_new <- principalNetworks(g1)
  expect_equal(PN_new$eigenvalues, PN$eigenvalues)
  expect_equal(PN_new$eigenvectors, PN$eigenvectors)
  expect_equal(PN_new$loadings, PN$loadings)
  expect_equal(PN_new$eigenvalueThreshold, PN$eigenvalueThreshold)
  expect_equal(PN_new$edgeWeightThreshold, PN$edgeWeightThreshold)
  expect_equal(PN_new$components, PN$components)
  expect_equal(PN_new$scores, PN$scores)
  expect_equal(PN_new$componentGraphs[[1]]$getConnectedVertices(), PN$componentGraphs[[1]]$getConnectedVertices())
  expect_equal(PN_new$componentGraphs[[1]]$getEdgeDensity(), PN$componentGraphs[[1]]$getEdgeDensity())
  expect_equal(PN_new$residualGraphs[[1]]$getConnectedVertices(), PN$residualGraphs[[1]]$getConnectedVertices())
})