.TH "rfmt" 1

.SH NAME
rfmt \- Format text to avoid line breaks inside words

.SH SYNOPSIS
.B rfmt \fIline_length

.SH DESCRIPTION
The \fBrfmt\fR program is a simple reformatter which copies standard input to standard output such that each output line is no longer than \fIline_length\fR characters. The program also ensures that line breaks will not occur in the middle of words, so some lines may be shorter than this maximum. The effect is very similar to \fBfmt\fR(1), except that no other reformatting will take place, such as the removal of whitespace at the beginning of lines.
.PP
The program requires \fBruby\fR(1) to run.

.SH EXAMPLES
The effect of the program can be quickly seen by running
.TP
.PP
echo The quick brown fox jumped | rfmt 10
.TP
No more than ten characters will appear on each line.

.SH AUTHOR
Jon Clayden <jon.clayden+tractor@gmail.com>
