.TH "tractor" 1

.SH NAME
tractor \- Command line interface for the TractoR MRI analysis project

.SH SYNOPSIS
.B tractor \-h
.br
.B tractor \-o \fR[\fB\-w \fIworking_dir\fR]\fB \fIscript\fB
.br
.B tractor \fR[\fB\-ldqr\fR] [\fB\-v \fIlevel\fR] [\fB\-w \fIworking_dir\fR] [\fB\-c \fIconfig_file\fR] \fIscript \fR[\fIarg1\fB \fR[\fIarg2 ...\fR]]\fB

.SH DESCRIPTION
The \fIscript\fR, a text file containing R code, need not be specified with the '\.R' extension. The program searches in the current working directory for the specified script first, followed by any directory specified using the '-w' option, then ~/\.tractor and finally /etc/tractor. Any \fIscript\fR not in one of these locations must be specified using its full path.

.SH OPTIONS
.TP
.B \-h
Display usage information and quit.
.TP
.B \-o
Do not run the script, but instead produce a list of the options that it supports, along with their default values.
.TP
.B \-l
Direct output to a log file as well as \fIstdout\fR.
.TP
.B \-d
Produce debugging output; equivalent to '\-v 3'.
.TP
.B \-q
Run in quiet mode; the tractor script will not produce any output of its own.
.TP
.B \-r
Produce a report file in the working directory (if anything is reported by the experiment script).
.TP
.B \-v \fIlevel\fB
Produce verbose output: the \fIlevel\fR determines the amount of extra information reported, from 1 (least) to 3 (most).
.TP
.B \-w \fIworking_dir\fB
Specify the working directory for the experiment, which will be created if necessary (default is the current directory).
.TP
.B \-c \fIconfig_file\fB
Specify a configuration file in YAML format.

.SH DIAGNOSTICS
Return value is 0 if no errors were generated by the experiment script, and 1 otherwise. The exact number of errors and warnings generated is written to \fIstdout\fR unless the \fB\-q\fR flag is given.

.SH BUGS
